# Adsum Analysis Options
# Using very_good_analysis for strict linting

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat info level as warnings for stricter enforcement
    todo: ignore  # Allow TODO comments during development
    
linter:
  rules:
    # Allow some flexibility during development
    public_member_api_docs: false  # Re-enable for production
    
    # Strict rules we want
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_print: true  # Use AppLogger instead
    
    # Flutter specific
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_declarations: true
